includes:
  - https://github.ibm.com/cloud-docs/ha-infrastructure
  - https://github.ibm.com/cloud-docs/virtual-servers
  - https://github.ibm.com/cloud-docs/bare-metal
translation:
  exclude:
    byFilePath:
      - file-dont-translate.md
      - folder-dont-translate/  
